name: SurvivalEnhanced
version: '${project.version}'
main: plugins.larskrs.net.survivalenhanced.SurvivalEnhanced
api-version: 1.19
description: "This is my wierd description that someone required me to write about my random features packed survival plugin."

softdepend:
  - Vault
  - Citizens

permissions:
  survivalenhanced.command.prefix:
    default: not op
    description: Players with this can use the prefix command to set their own prefix.
  survivalenhanced.command.prefix.admin:
    default: op
    description: Allows admins to add, remove and set others prefixes.
  survivalenhanced.command.stable.tp:
    default: op
    description: Allows admins to tp to stables.
  survivalenhanced:
    default: not op
    description: Essential for the plugin to be used by your players.
  survivalenhanced.stable.create:
    default: not op
    description: Allows you to create your own stable.
  survivalenhanced.stable.delete.bypass:
    default: op
    description: Allows admins to override the stable deletion restriction that prevents non stable owners to delete stables.
  survivalenhanced.command.enchant:
    default: op
  survivalenhanced.command.skull:
    default: op
  survivalenhanced.command.rtp:
    default: op
  survivalenhanced.command.steed:
    default: op
  survivalenhanced.command.dungeon:
    default: op
  survivalenhanced.command.hat:
  survivalenhanced.command.hat.give:
    default: op



# Staff Commands

  survivalenhanced.command.spawnmob:
    default: op
  survivalenhanced.command.world:
    default: op
  survivalenhanced.command.watchover:
    default: op
    description: Command to let admins manage and view players.
  survivalenhanced.command.vanish:
    default: op
    description: Command to let admins hide themselves from players.
  survivalenhanced.vanish.see:
    default: op
    description: Permission to see others who are vanished.

